### ISSUE TITLE
Basic usage of parsing string fails with `isNil` is a user defined error

### ISSUE THREAD

**Issue by xmonader** [NimParsers/parsetoml#23] opened 2018-09-19 11:43 UTC
```
import parsetoml


let table1 = parsetoml.parseString(""""
[input]
file_name = "test.txt"

[output]
verbose = true
""")
```

error: 
```
.nimble/pkgs/parsetoml-0.3.2/parsetoml.nim(1284, 8) Error: usage of 'isNil' is a user-defined error
```

I'm using nim head

**Comment by xmonader** [comment] 2018-09-19 11:51
also when compiling with --nilseqs:on 
```
import parsetoml


let table1 = parsetoml.parseString(""""
[input]
file_name = "test.txt"

[output]
verbose = true
""")
```
gives 

```
testtoml.nim(4)          testtoml
parsetoml.nim(991)       parseString
parsetoml.nim(985)       parseStream
parsetoml.nim(763)       parseKeyValuePair
Error: unhandled exception: (3:12) key names cannot contain spaces [TomlError]
Error: execution of an external program failed: '/home/ahmed/testtoml '
```

**Comment by kaushalmodi** [comment] 2018-09-19 12:07
I think that error is because of using 4 instead of 3 quotes on line 3:

```
let table1 = parsetoml.parseString(""""
```

**Comment by xmonader** [comment] 2018-09-19 13:21
@kaushalmodi you're correct my bad thanks

**Comment by kaushalmodi** [comment] 2018-09-19 13:22
The issue is still not technically closed, right? It would still fail on devel when not using that switch, right?

**Comment by PMunch** [comment] 2018-09-19 13:23
Yeah, the error message is strange but it's cause by the four `"` characters. Should probably be a better error message. And we should update this to work with the new nil behaviour so I'm keeping this open for now.

**Comment by iffy** [comment] 2018-09-20 03:45
I'm getting the same error message for this code:

```nim
import strutils
import strformat
import parseopt

var
    filename: string
var p = initOptParser()
for kind, key, val in p.getopt():
    case kind
    of cmdArgument:
        filename = key
    of cmdLongOption:
        discard
    of cmdShortOption:
        discard
    of cmdEnd:
        discard
if filename.isNil():
    echo "Error: provide a filename"
    quit(1)

echo "Success"
```

How should I check if a string is nil?

**Comment by PMunch** [comment] 2018-09-20 06:02
You can't any longer, you just check if it is equal to `""`. Libraries that used nil checking should switch over to using options

EDIT: Of course in that case you should simply  check if `filename` exists on the filesystem.

**Comment by PMunch** [comment] 2018-09-20 21:39
This should be fixed in https://github.com/NimParsers/parsetoml/commit/6ed000e175021ad4cadb6d0149bd6d752ffa16ed

**Closed as completed by PMunch** 2018-09-20 21:39 UTC
